apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil-playground
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30080