# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	config.vm.define "lumenthiS" do |lumenthiS|
		lumenthiS.vm.hostname = "lumenthiS"
		lumenthiS.vm.network "private_network",
			:ip => "192.168.42.110"
		lumenthiS.vm.provider :libvirt do |libvirt|
			libvirt.cpus = 4
			libvirt.memory = 4096
			libvirt.management_network_name = 'vagrant-libvirt'
			libvirt.management_network_address = '192.168.42.2/24'
		end
		lumenthiS.vm.provision :shell, path: "scripts/centos-gitlab.sh", run: 'always'
	end
end
