

MASTER_NODE = 'TlaraineS'
MASTER_HOSTNAME = 'TlaraineS'
MASTER_IP = '192.168.56.110'


# machines config
MEM = 4096
CPU = 4

# create machines config
Vagrant.configure("2") do |config|
	config.vm.box = "bento/debian-11"
	config.vm.box_url = "file:///home/tlaraine/21-school/iot/debian11.box"
	
	config.vm.provider "virtualbox" do |v|
		v.memory = MEM
		v.cpus = CPU
		# for connect with SSH on both machines with no password
		id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
  		config.vm.provision "copy ssh public key", type: "shell",
    	  inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
	end

  # master node config
	config.vm.define MASTER_NODE do |master|
		master.vm.hostname = MASTER_HOSTNAME
		master.vm.network :private_network, ip: MASTER_IP
		# configure shared folder
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		# run script for master node with argument
		master.vm.provision "shell", privileged: true, path: "scripts/debian-gitlab.sh", args: [MASTER_IP]
		master.vm.provider "virtualbox" do |v|
			v.name = MASTER_NODE
		end
	end
end